(()=>{if(window.__summaryV12)return;window.__summaryV12=true;
const presets=['Conta de luz','Cartão de crédito Thayna','Cartão de crédito Elias','Internet fixa','Celular Elias','Celular Thayna','Financiamento apartamento','Financiamento moto Thayna','Condomínio','IPTU','Entrada parcelada'];
function instalarCategorias(){const nome=document.getElementById('nome');if(!nome)return;let wrap=document.getElementById('contaCategoriaWrap');if(!wrap){wrap=document.createElement('div');wrap.id='contaCategoriaWrap';wrap.style.cssText='margin-bottom:8px';const sel=document.createElement('select');sel.id='contaCategoriaSelect';sel.style.width='100%';sel.innerHTML='<option value="">Selecionar conta</option>'+presets.map(x=>'<option value="'+x+'">'+x+'</option>').join('')+'<option value="__outro__">Outra conta (digitar manualmente)</option>';wrap.appendChild(sel);nome.parentNode.insertBefore(wrap,nome);sel.addEventListener('change',()=>{if(sel.value==='__outro__'){nome.value='';nome.focus()}else if(sel.value){nome.value=sel.value;nome.dispatchEvent(new Event('input',{bubbles:true}));nome.dispatchEvent(new Event('change',{bubbles:true}))}})}nome.placeholder='Ou digite o nome da conta';}
instalarCategorias();new MutationObserver(()=>instalarCategorias()).observe(document.body,{childList:true,subtree:true});
const box=document.getElementById('custoMensal');if(!box)return;
const tipos=['mes','atraso','geral',...CATS];
function itemConta(c){return '<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><b>'+esc(c.nome||'Conta')+'</b><div class="muted">'+fmt.format(Number(c.valor||0))+' · vence '+br(c.vencimento)+' · '+esc(c.status||'')+'</div>'+(c.observacoes?'<div style="margin-top:4px">📝 '+esc(c.observacoes)+'</div>':'')+'</div>'}
function itemGasto(g){return '<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><b>'+esc(g.descricao||g.categoria||'Gasto')+'</b><div class="muted">'+fmt.format(Number(g.valor||0))+' · '+br(g.data)+'</div>'+(g.observacoes?'<div style="margin-top:4px">📝 '+esc(g.observacoes)+'</div>':'')+'</div>'}
function dados(tipo){const n=new Date(),hoje=iso(n);const cm=contas.filter(c=>{const d=new Date(c.vencimento+'T12:00');return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()});const gm=gastos.filter(g=>{const d=new Date(g.data+'T12:00');return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()});const at=contas.filter(c=>c.status!=='pago'&&c.vencimento<hoje);if(tipo==='mes')return{title:'💰 Contas do mês',body:cm.map(itemConta).join('')||'<p class="muted">Nenhuma conta neste mês.</p>'};if(tipo==='atraso')return{title:'🔴 Contas em atraso',body:at.map(itemConta).join('')||'<p class="muted">Nenhuma conta em atraso.</p>'};if(tipo==='geral')return{title:'💸 Total geral a pagar',body:'<h3>Contas do mês</h3>'+(cm.map(itemConta).join('')||'<p class="muted">Nenhuma.</p>')+'<h3>Contas em atraso</h3>'+(at.map(itemConta).join('')||'<p class="muted">Nenhuma.</p>')+'<h3>Gastos extras do mês</h3>'+(gm.map(itemGasto).join('')||'<p class="muted">Nenhum.</p>')};const arr=gm.filter(g=>g.categoria===tipo);return{title:tipo,body:arr.map(itemGasto).join('')||'<p class="muted">Nenhum lançamento de '+esc(tipo)+' neste mês.</p>'}}
let modal=document.getElementById('resumoV12');if(!modal){modal=document.createElement('div');modal.id='resumoV12';modal.style.cssText='display:none;position:fixed;inset:0;background:#0008;align-items:center;justify-content:center;padding:16px;z-index:15000';modal.innerHTML='<div class="card" style="width:min(580px,100%);max-height:88vh;display:flex;flex-direction:column;overflow:hidden;padding:0"><div style="padding:18px 18px 10px;display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 id="v12Title" style="margin:0"></h2><button id="v12Close" class="secondary">✕</button></div><div id="v12Body" style="padding:0 18px 16px;overflow:auto;flex:1"></div><div style="padding:12px 18px 18px;border-top:1px solid #e5e7eb;background:#fff"><button id="v12Wa" class="wa" style="width:100%;font-size:16px">📲 Enviar por WhatsApp</button></div></div>';document.body.appendChild(modal);document.getElementById('v12Close').onclick=()=>modal.style.display='none';modal.addEventListener('click',e=>{if(e.target===modal)modal.style.display='none'})}
function abrir(tipo){const d=dados(tipo);document.getElementById('v12Title').textContent=d.title;document.getElementById('v12Body').innerHTML=d.body;document.getElementById('v12Body').scrollTop=0;document.getElementById('v12Wa').onclick=()=>{const t=(document.getElementById('v12Title').innerText+'\n\n'+document.getElementById('v12Body').innerText).replace(/\n{3,}/g,'\n\n').trim();location.href='https://wa.me/?text='+encodeURIComponent(t)};modal.style.display='flex'}
function marcar(){[...box.children].filter(x=>x.nodeType===1).forEach(c=>{c.style.setProperty('border','1px solid #e5e7eb','important');c.style.setProperty('outline','none','important');c.style.setProperty('box-shadow','none','important');c.style.cursor='pointer';c.style.touchAction='manipulation'})}
box.addEventListener('click',e=>{const card=e.target.closest('#custoMensal > *');if(!card)return;const all=[...box.children].filter(x=>x.nodeType===1),i=all.indexOf(card);if(i<0||!tipos[i])return;e.preventDefault();e.stopPropagation();abrir(tipos[i])},true);
new MutationObserver(marcar).observe(box,{childList:true,subtree:true});marcar();
})();