(()=>{if(window.__summaryV14)return;window.__summaryV14=true;
const presets=['Conta de luz','Cartão de crédito Thayna','Cartão de crédito Elias','Internet fixa','Celular Elias','Celular Thayna','Financiamento apartamento','Financiamento moto Thayna','Condomínio','IPTU','Entrada parcelada'];
function instalarCategorias(){const nome=document.getElementById('nome');if(!nome)return;if(document.getElementById('contaCategoriaSelect'))return;const sel=document.createElement('select');sel.id='contaCategoriaSelect';sel.innerHTML='<option value="">Selecione a conta</option>'+presets.map(x=>'<option value="'+x+'">'+x+'</option>').join('')+'<option value="__outro__">Outra conta...</option>';sel.style.cssText='width:100%;min-height:48px';nome.parentNode.insertBefore(sel,nome);nome.style.display='none';sel.addEventListener('change',()=>{if(sel.value==='__outro__'){nome.style.display='block';nome.value='';nome.placeholder='Digite o nome da conta';nome.focus()}else{nome.style.display='none';nome.value=sel.value||'';nome.dispatchEvent(new Event('input',{bubbles:true}));nome.dispatchEvent(new Event('change',{bubbles:true}))}})}
instalarCategorias();
function setupMonthNav(){const periodo=document.getElementById('periodo');if(!periodo||document.getElementById('mesNavWrap'))return;const wrap=document.createElement('div');wrap.id='mesNavWrap';wrap.style.cssText='display:none;align-items:center;justify-content:space-between;gap:12px;margin:18px 0 8px';const prev=document.createElement('button');prev.className='secondary';prev.textContent='‹';prev.style.cssText='font-size:32px;font-weight:700;line-height:1;padding:7px 18px;min-width:54px';const title=document.createElement('h3');title.style.cssText='margin:0;text-align:center;font-size:24px;flex:1';const next=document.createElement('button');next.className='secondary';next.textContent='›';next.style.cssText=prev.style.cssText;wrap.append(prev,title,next);periodo.parentNode.insertBefore(wrap,periodo);const update=()=>{const mensal=view==='mes';wrap.style.display=mensal?'flex':'none';periodo.style.display=mensal?'none':'';if(mensal)title.textContent='🗓️ '+calDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};prev.onclick=()=>{calDate.setMonth(calDate.getMonth()-1);render();update()};next.onclick=()=>{calDate.setMonth(calDate.getMonth()+1);render();update()};document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(update,0)));update()}
setupMonthNav();
const box=document.getElementById('custoMensal');if(!box)return;const tipos=['mes','atraso','geral',...CATS];
function itemConta(c){return '<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><b>'+esc(c.nome||'Conta')+'</b><div class="muted">'+fmt.format(Number(c.valor||0))+' · vence '+br(c.vencimento)+' · '+esc(c.status||'')+'</div>'+(c.observacoes?'<div style="margin-top:4px">📝 '+esc(c.observacoes)+'</div>':'')+'</div>'}
function itemGasto(g){return '<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><b>'+esc(g.descricao||g.categoria||'Gasto')+'</b><div class="muted">'+fmt.format(Number(g.valor||0))+' · '+br(g.data)+'</div>'+(g.observacoes?'<div style="margin-top:4px">📝 '+esc(g.observacoes)+'</div>':'')+'</div>'}
function gastosMes(){const n=new Date();return gastos.filter(g=>{const d=new Date(g.data+'T12:00');return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()})}
function dados(tipo){const n=new Date(),hoje=iso(n);const cm=contas.filter(c=>{const d=new Date(c.vencimento+'T12:00');return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()});const gm=gastosMes();const at=contas.filter(c=>c.status!=='pago'&&c.vencimento<hoje);if(tipo==='mes')return{title:'💰 Contas do mês',body:cm.map(itemConta).join('')||'<p class="muted">Nenhuma conta neste mês.</p>'};if(tipo==='atraso')return{title:'🔴 Contas em atraso',body:at.map(itemConta).join('')||'<p class="muted">Nenhuma conta em atraso.</p>'};if(tipo==='geral'){const pend=contas.filter(c=>c.status!=='pago');return{title:'💸 Total geral a pagar',body:pend.map(itemConta).join('')||'<p class="muted">Nenhuma conta pendente.</p>'}}const arr=gm.filter(g=>g.categoria===tipo);return{title:tipo,body:arr.map(itemGasto).join('')||'<p class="muted">Nenhum lançamento de '+esc(tipo)+' neste mês.</p>'}}
function textoGeral(){const pend=contas.filter(c=>c.status!=='pago'),gm=gastosMes();const a=pend.reduce((s,c)=>s+Number(c.valor||0),0),b=gm.reduce((s,g)=>s+Number(g.valor||0),0);let linhas=['💸 *Total geral a pagar*','','📌 *Contas pendentes*'];if(pend.length)pend.forEach(c=>linhas.push('• '+(c.nome||'Conta')+': '+fmt.format(Number(c.valor||0))+' | vence '+br(c.vencimento)));else linhas.push('Nenhuma conta pendente.');linhas.push('','🛒 *Gastos extras do mês:* '+fmt.format(b),'','Contas pendentes: '+fmt.format(a),'Gastos extras: '+fmt.format(b),'*TOTAL: '+fmt.format(a+b)+'*');return linhas.join('\n')}
let modal=document.getElementById('resumoV14');if(!modal){modal=document.createElement('div');modal.id='resumoV14';modal.style.cssText='display:none;position:fixed;inset:0;background:#0008;align-items:center;justify-content:center;padding:16px;z-index:15000';modal.innerHTML='<div class="card" style="width:min(580px,100%);max-height:88vh;display:flex;flex-direction:column;overflow:hidden;padding:0"><div style="padding:18px 18px 10px;display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 id="v14Title" style="margin:0"></h2><button id="v14Close" class="secondary">✕</button></div><div id="v14Body" style="padding:0 18px 16px;overflow:auto;flex:1"></div><div style="padding:12px 18px 18px;border-top:1px solid #e5e7eb;background:#fff"><button id="v14Wa" class="wa" style="width:100%;font-size:16px">📲 Enviar por WhatsApp</button></div></div>';document.body.appendChild(modal);document.getElementById('v14Close').onclick=()=>modal.style.display='none';modal.addEventListener('click',e=>{if(e.target===modal)modal.style.display='none'})}
function abrir(tipo){const d=dados(tipo);document.getElementById('v14Title').textContent=d.title;document.getElementById('v14Body').innerHTML=d.body;document.getElementById('v14Body').scrollTop=0;document.getElementById('v14Wa').onclick=()=>{const t=tipo==='geral'?textoGeral():(document.getElementById('v14Title').innerText+'\n\n'+document.getElementById('v14Body').innerText).replace(/\n{3,}/g,'\n\n').trim();const u='https://api.whatsapp.com/send?text='+encodeURIComponent(t);window.open(u,'_top')};modal.style.display='flex'}
function marcar(){[...box.children].filter(x=>x.nodeType===1).forEach(c=>{c.style.setProperty('border','1px solid #e5e7eb','important');c.style.setProperty('outline','none','important');c.style.setProperty('box-shadow','none','important');c.style.cursor='pointer';c.style.touchAction='manipulation'})}
box.addEventListener('click',e=>{const card=e.target.closest('#custoMensal > *');if(!card)return;const all=[...box.children].filter(x=>x.nodeType===1),i=all.indexOf(card);if(i<0||!tipos[i])return;e.preventDefault();e.stopPropagation();abrir(tipos[i])},true);new MutationObserver(marcar).observe(box,{childList:true,subtree:true});marcar();
})();